apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::090952272468:role/eksctl-eksworkshop-eksctl-nodegro-NodeInstanceRole-1QJJYXBY3S5RY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::090952272468:role/Inho-Lambda-Role
      username: kubernetes-admin
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::090952272468:user/lab-admin
      username: admin
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-21T09:59:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "600320"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 37532aab-93ea-4325-926a-3fb0b8eac8b6
